### ISSUE TITLE
Custom banner at top page

### ISSUE THREAD

**Issue by humitos** [humitos/sphinx-version-warning#13]
Example: http://flask.pocoo.org/docs/dev/

**Comment by sloria** [comment]
I'm trying to achieve this for marshmallow. I tried using the following config:

https://github.com/marshmallow-code/marshmallow/blob/5f2470470ab29f9fa87341db118c55cd00a2916e/docs/conf.py#L104-L120

But `versionwarning_body_default_selector` and `versionwarning_body_extra_selector` didn't have any effect, since [process_version_warning_banner](https://github.com/humitos/sphinx-version-warning/blob/c4e2f6783a7de70c52ce7ae646a67c9091be2fc9/versionwarning/signals.py#L12) doesn't seem to respect those options.

## Expected result 

![image 2018-08-04 11-11-20](https://user-images.githubusercontent.com/2379650/43677855-27cfb770-97d7-11e8-8cf3-7813278e98da.png)

## Actual result

![image 2018-08-04 11-13-03](https://user-images.githubusercontent.com/2379650/43677878-73877a5e-97d7-11e8-89e0-c3cee9d26888.png)

**Comment by humitos** [comment]
Thanks for posting it here.

> But versionwarning_body_default_selector and versionwarning_body_extra_selector didn't have any effect, since process_version_warning_banner doesn't seem to respect those options.

Yes, `process_version_warning_banner` doesn't respect this. Those values are considered only when the banner is injected dynamically by Javascript.

Currently, there are two ways of inserting the banner: statically (done by Python/Sphinx as a `docutils` node) or dynamically (done via Javascript).

When injecting the banner statically, this is injected as a first node of the reST document (https://github.com/humitos/sphinx-version-warning/blob/master/versionwarning/signals.py#L21). So, there is not too much the extension can do here.

The HTML structure is managed by the Sphinx theme, so to change that, the Sphinx theme has to be altered. `flask` theme alters this by rendering the version warning without being part of the reST document: https://github.com/pallets/pallets-sphinx-themes/blob/master/src/pallets_sphinx_themes/themes/pocoo/layout.html#L19-L21

**Comment by humitos** [comment]
This is a **completely** _hack_...

In case you _really_, _really_ want this and _do_ **not** want to create/adapt a theme and _you don't care about this hack_, you can create a simple JS and add it to project with this code:

```javascript
$(document).ready(function () {
    $('#version-warning-banner').prependTo($('div.document'))
});
```

That will move the HTML of the banner before the document itself :grimacing: 

Remember to add this file into your `conf.py`:

```python
def setup(app):
    app.add_javascript('js/movebanner.js')

```

Check the example at: https://sphinx-version-warning-example.readthedocs.io/en/flask-like-warning/

**Comment by sloria** [comment]
marshmallow is already using my fork of alabaster, so I don't have a problem modifying the theme. Would it be feasible for sphinx-version-warning to add the version warning banner to the template context so I could just drop it into the layout?

**Comment by humitos** [comment]
@sloria I've been thinking on your needings here and I found that maybe I need to change the design of the extension.

As I commented in this issue, there are two ways of generating the banner: dynamically (via Javascript) and statically (via Sphinx/docutils admonition node).

When I design it, I was thinking that if you already know the banner that you want to show in a specific version that was a great use case for the static case, but now I'm thinking that this complicates things. Why? Because if you tweak the HTML from the config and use a custom selector (as you mentioned) that won't be reflected in any static-generated banner.

Looking for feedback:

1. do you think it could have any drawback if I remove completely the static way of adding the banner and only relies on the dynamic one?
1. do you think there is an _amazing_ use case for the static banner that I'm missing and can't be achieved with the dynamic one?
1. do you think... (whatever you want to add here)?

> As as a side note, Read the Docs only adds the banner dynamically and this has been working fine since it was implemented.

**Comment by sloria** [comment]
I think only using the dynamic approach makes sense for both maintainability of this package and for the sake of being able to place the banner anywhere.

**Comment by humitos** [comment]
@sloria I started working on this. I opened #15 for this and did a _very simple_ test at https://sphinx-version-warning-example.readthedocs.io/en/flask-like-warning/

I need to keep working on this for a proper release, though.

**Comment by sloria** [comment]
Great! Looking forward to it.

**Comment by humitos** [comment]
@sloria I just released v1.0.0 and you should be able to customize with your needings. Please, let me know if this does work.

**Comment by humitos** [comment]
Weird. One of my tests was with Sphinx 1.8. I'll check this again and fix it.

Thanks for the report. Hopefully, you will be able to use this extension soon 😊

**Comment by humitos** [comment]
Weird. One of my tests was with Sphinx 1.8. I'll check this again and fix it.

Thanks for the report. Hopefully, you will be able to use this extension soon 😊

**Comment by sloria** [comment]
No worries. I've just pinned to sphinx==1.7.9 for the time being.
