### ISSUE TITLE
Unable to run version warning with URL different than readthedocs

### ISSUE THREAD

**Issue by aanm** [humitos/sphinx-version-warning#23]
```
Failed to load https://readthedocs.org/api/v2/version/?project__slug=cilium&active=true: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://docs.cilium.io' is therefore not allowed access.
```
Open console in:
http://docs.cilium.io/en/v1.0/

This works URL works:
https://cilium.readthedocs.io/en/v1.0/

@humitos what do you think it should be the best option for this?

Should I create a copy of the JSON from `https://readthedocs.org/api/v2/version/?project__slug=cilium&active=true` in `http://docs.cilium.io/version` plus add `versionwarning_api_url=docs.cilium.io`?

**Comment by humitos** [comment]
> Should I create a copy of the JSON from `https://readthedocs.org/api/v2/version/?project__slug=cilium&active=true` in `http://docs.cilium.io/version` plus add `versionwarning_api_url=docs.cilium.io`?

Nope, this won't work.

The problem is because of CORS. There is not too much we can do from this extension since that endpoint does not support `jsonp`. This is something that has to be fixed in Read the Docs. It may worth to open an issue there.

**Comment by humitos** [comment]
@aanm I opened a PR under Read the Docs to discuss this problem. Please, subscribe there. Thanks.

**Comment by humitos** [comment]
@aanm the upstream PR was merged today and it will be deployed soon. When that happens, this issue will be automatically fixed.

**Comment by aanm** [comment]
@humitos thank you very much!

**Comment by ericholscher** [comment]
I believe this should now be deployed. 👍

**Comment by humitos** [comment]
Thanks!

I just tested the links from the description and both works as expected.

Closing here.

**Comment by aanm** [comment]
@humitos was there a regression introduced in RTD? We seem to be seeing this exact issue again

**Comment by humitos** [comment]
Hi @aanm! I'm not sure to understand the problem you are reporting. Going to https://docs.cilium.io/en/v1.10/ I do see the warning version without problem. The console shows the debug information properly.

**Comment by aanm** [comment]
Hi @humitos thanks for the reply. It is working now for v1.9 and v1.10 because we have made some changes on our side, see https://github.com/cilium/cilium/pull/19563, https://github.com/cilium/cilium/pull/19610 and https://github.com/cilium/cilium/pull/19611. We have backported those changes to those branches. However, if you look at https://docs.cilium.io/en/v1.8/ you can still see the CORS problem in the console. 

Thanks!

**Comment by humitos** [comment]
@stsewd do you know what happened here and why the API is now having CORS issues? Is it possible to solve it somehow?

**Comment by stsewd** [comment]
Looks like this was the result from where we locked down our API from cross site requests https://github.com/readthedocs/readthedocs.org/security/advisories/GHSA-3v5m-qmm9-3c6c.

We could:

- Allow access to api/v2 on .org only (this could be confusing for .com users)
- Allow access only if the project is public and return public versions only (this needs some changes on our app to extract the project from the request and have it list public versions only on cross site requests)
- Implement our new footer API, so we can get this information from the same domain.
