### ISSUE TITLE
Can this work without hosting on ReadTheDocs?

### ISSUE THREAD

**Issue by darkvertex** [humitos/sphinx-version-warning#38]
Hi,

I'm building some docs for internal company use and we don't host them publicly.

I was wondering if there is a workflow to make this work without ReadTheDocs hosting if I'm still using the popular RTD theme? It didn't seem very clear from the README.

**Comment by humitos** [comment]
Hi @darkvertex 👋🏼 . This extension is not thought to work outside Read the Docs, no.

We are in the process of deprecating it in favor of the new addons notification we are building: https://github.com/readthedocs/addons/tree/humitos/readme-small-update#non-stable-version-warning-banner

So, I would assume that sooner than later we are going to archive this repository/extension.
